analys:
  outputs:
    dev:
      dataset: dreamshop_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/dags/dbt/analys/capstone_bigquery_key.json
      location: US
      method: service-account
      priority: interactive
      project: capstone-project-alta
      threads: 1
      type: bigquery
  target: dev
